name: washsync_app
description: WashSync Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase & Backend ---
  firebase_core: ^3.7.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.0

  # --- Image & File Handling ---
  image_picker: ^1.1.2
  path: ^1.9.0             # Added: Helps with naming files for upload

  # --- Notifications & Timing ---
  flutter_local_notifications: ^17.2.1 
  timezone: ^0.9.4
  intl: ^0.19.0            # Crucial for Date/Time formatting in History

  # --- UI & Utilities ---
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/imcons/logoWashSync.png"

flutter_native_splash:
  color: "#E6C6FF"  
  background_image: assets/images/logoWashSync.png

  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/